import React from "react";
import Link from "next/link";
import {
  Sparkles,
  Play,
  Heart,
  MessageSquare,
  Share2,
  Compass,
  Film,
  Timer,
} from "lucide-react";
import MainLayout from "../../component/MainLayout";
import { fetchApi } from "@/lib/api";
import ExploreFeed from "./ExploreFeed";
import ExplorePublishButton from "./ExplorePublishButton";
import ExploreSearch from "./ExploreSearch";

export default async function ExplorePage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const params = await searchParams;
  const mode = (params.mode as string) || 'trending';
  const topic = (params.topic as string) || '';

  let forYouData: any = { data: [] };
  let exploreData: any = { data: [] };
  
  let isAuthenticated = false;
  let userJobs: any[] = [];
  try {
    const me = await fetchApi('/users/me');
    isAuthenticated = !!me;
    
    if (isAuthenticated) {
      const jobsRes = await fetchApi('/jobs').catch(() => []);
      userJobs = Array.isArray(jobsRes) ? jobsRes : [];
    }
  } catch (e) {
    // Guest user
  }

  try {
    if (topic) {
      // Search mode active
      exploreData = await fetchApi(`/explore/search?topic=${encodeURIComponent(topic)}&limit=10`);
    } else {
      // Standard feed mode
      if (isAuthenticated) {
        forYouData = await fetchApi('/explore/for-you?limit=2');
      } else {
        forYouData = await fetchApi('/explore?mode=trending&limit=2');
      }
      exploreData = await fetchApi(`/explore?limit=10&mode=${mode}`);
    }
  } catch (error) {
    console.error("Failed to fetch explore data:", error);
  }

  const items = exploreData?.data || [];
  const nextCursor = exploreData?.nextCursor || null;
  const featuredItems = forYouData?.data || [];

  const displayFeatured1 = featuredItems[0];
  const displayFeatured2 = featuredItems[1];

  return (
    <MainLayout activePage="explore">
      <div className="max-w-6xl mx-auto">
        {/* Page Header */}
        <div className="flex items-end justify-between mb-8">
          <div className="max-w-xl">
            <h2 className="text-3xl font-bold text-slate-900 mb-2">{topic ? `Search: ${topic}` : "Explore"}</h2>
            <p className="text-slate-500 text-sm">
              {topic ? "Showing results for your topic." : "Discover the latest cinematic masterpieces generated by the Neura Gen community."}
            </p>
          </div>

          <div className="flex items-center gap-4">
            <ExploreSearch />

          {/* Trending/New Toggle */}
          <div className="flex bg-slate-50 p-1 rounded-full border border-slate-100">
            <Link 
              href="?mode=trending"
              className={`px-6 py-2 text-sm font-medium rounded-full transition-colors ${mode === 'trending' ? 'bg-white text-indigo-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
            >
              Trending
            </Link>
            <Link 
              href="?mode=new"
              className={`px-6 py-2 text-sm font-medium rounded-full transition-colors ${mode === 'new' ? 'bg-white text-indigo-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
            >
              New
            </Link>
          </div>
        </div>
        </div>

        {/* For You Section - Hide during search */}
        {!topic && (
          <div className="mb-12">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-indigo-600" />
              <h3 className="text-xl font-bold text-slate-900">For You</h3>
            </div>
            <button className="text-indigo-600 text-sm font-medium hover:underline">
              See all
            </button>
          </div>

          {displayFeatured1 || displayFeatured2 ? (
            <div className="grid grid-cols-12 gap-6 h-[400px]">
              {/* Featured Card Left */}
              {displayFeatured1 && (
                <div className="col-span-8 relative rounded-2xl overflow-hidden group cursor-pointer shadow-sm block">
                  <Link href={`/post/${displayFeatured1.postId || displayFeatured1.id}`} className="absolute inset-0 z-10" />
                  {(() => {
                    const videoUrl = displayFeatured1.videoUrl || displayFeatured1.post?.videoUrl || displayFeatured1.assetVersion?.fileUrl;
                    const thumbnailUrl = displayFeatured1.thumbnailUrl || displayFeatured1.post?.thumbnailUrl;
                    const isVideo = !!videoUrl && (displayFeatured1.assetVersion?.mimeType?.startsWith('video/') || /\.(mp4|webm|mov)(\?|$)/i.test(videoUrl));
                    const displayUrl = videoUrl || "https://images.unsplash.com/photo-1605806616949-1e87b487cb2a?auto=format&fit=crop&q=80&w=1200";
                    
                    return isVideo ? (
                      <video src={displayUrl} poster={thumbnailUrl || undefined} className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" autoPlay loop muted playsInline />
                    ) : (
                      <img src={thumbnailUrl || displayUrl} alt={displayFeatured1.title || "Featured Video"} className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                    );
                  })()}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent p-6 flex flex-col justify-end pointer-events-none">
                    <div className="mb-auto mt-2 pointer-events-auto relative z-20 w-fit">
                      <span className="bg-indigo-600 text-white text-xs font-bold px-3 py-1 rounded-full tracking-wide">
                        {isAuthenticated ? 'FOR YOU' : 'TRENDING'}
                      </span>
                    </div>
                    <div className="flex justify-between items-end pointer-events-auto relative z-20">
                      <div>
                        <h4 className="text-3xl font-bold text-white mb-3">
                          {displayFeatured1.title || "Untitled Video"}
                        </h4>
                        <Link href={`/user/${displayFeatured1.post?.user?.id || displayFeatured1.post?.user?.username || 'unknown'}`} className="flex items-center gap-2 text-white/80 text-sm hover:text-white transition-colors w-fit">
                          <img
                            src={displayFeatured1.post?.user?.avatarUrl || `https://ui-avatars.com/api/?name=${encodeURIComponent(displayFeatured1.post?.user?.username || "Creator")}&background=e0e7ff&color=4f46e5`}
                            alt="Creator"
                            className="w-10 h-10 rounded-full border-2 border-white object-cover bg-slate-100"
                          />
                          <div className="flex-1 min-w-0">
                            <p className="font-medium truncate">{displayFeatured1.post?.user?.username || "Unknown Creator"}</p>
                          </div>
                        </Link>
                      </div>
                      <button className="bg-white/20 backdrop-blur-md hover:bg-white/30 text-white rounded-full p-4 transition-colors">
                        <Play className="h-6 w-6 fill-current" />
                      </button>
                    </div>
                  </div>
                </div>
              )}

              {/* Secondary Card Right */}
              {displayFeatured2 && (
                <div className="col-span-4 relative rounded-2xl overflow-hidden group cursor-pointer shadow-sm block">
                  <Link href={`/post/${displayFeatured2.postId || displayFeatured2.id}`} className="absolute inset-0 z-10" />
                  {(() => {
                    const videoUrl = displayFeatured2.videoUrl || displayFeatured2.post?.videoUrl || displayFeatured2.assetVersion?.fileUrl;
                    const thumbnailUrl = displayFeatured2.thumbnailUrl || displayFeatured2.post?.thumbnailUrl;
                    const isVideo = !!videoUrl && (displayFeatured2.assetVersion?.mimeType?.startsWith('video/') || /\.(mp4|webm|mov)(\?|$)/i.test(videoUrl));
                    const displayUrl = videoUrl || "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800";
                    
                    return isVideo ? (
                      <video src={displayUrl} poster={thumbnailUrl || undefined} className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" autoPlay loop muted playsInline />
                    ) : (
                      <img src={thumbnailUrl || displayUrl} alt={displayFeatured2.title || "Featured Video"} className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                    );
                  })()}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-transparent p-6 flex flex-col justify-end pointer-events-none">
                    <h4 className="text-xl font-bold text-white mb-2 relative z-20">
                      {displayFeatured2.title || "Untitled Video"}
                    </h4>
                    <Link href={`/user/${displayFeatured2.post?.user?.id || displayFeatured2.post?.user?.username || 'unknown'}`} className="text-white/80 text-sm hover:text-white transition-colors relative z-20 w-fit pointer-events-auto">@{displayFeatured2.post?.user?.username || "unknown"}</Link>
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="w-full h-32 flex items-center justify-center border border-slate-100 rounded-2xl bg-slate-50 text-slate-400 font-medium">
              Check back later for personalized recommendations.
            </div>
          )}
        </div>
        )}

        {/* Recent Discoveries Section */}
        <div>
          <div className="flex items-center gap-2 mb-6">
            <Compass className="h-5 w-5 text-indigo-600" />
            <h3 className="text-xl font-bold text-slate-900">
              {topic ? "Search Results" : "Recent Discoveries"}
            </h3>
          </div>

          <ExploreFeed initialItems={items} initialCursor={nextCursor} mode={mode} topic={topic} />
        </div>
      </div>
      <ExplorePublishButton jobs={userJobs} isAuthenticated={isAuthenticated} />
    </MainLayout>
  );
}
