import React from "react";
import Link from "next/link";
import {
  Sparkles,
  Play,
  Heart,
  MessageSquare,
  Share2,
  Compass,
  Film,
  Timer,
  Flame,
  Star,
  Clock
} from "lucide-react";
import MainLayout from "../../component/MainLayout";
import { fetchApi } from "@/lib/api";
import ExploreFeed from "./ExploreFeed";
import ExplorePublishButton from "./ExplorePublishButton";
import ExploreSearch from "./ExploreSearch";

export default async function ExplorePage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const params = await searchParams;
  const mode = (params.mode as string) || 'trending';
  const topic = (params.topic as string) || '';
  const sort = (params.sort as string) || '';
  const trending = params.trending === 'true';

  let forYouData: any = { data: [] };
  let exploreData: any = { data: [] };
  
  let isAuthenticated = false;
  let userJobs: any[] = [];
  try {
    const me = await fetchApi('/users/me');
    isAuthenticated = !!me;
    
    if (isAuthenticated) {
      const jobsRes = await fetchApi('/jobs').catch(() => []);
      userJobs = Array.isArray(jobsRes) ? jobsRes : [];
    }
  } catch (e) {
    // Guest user
  }

  // Adjust default mode if 'for_you' is requested but not authenticated
  const activeMode = mode === 'for_you' && !isAuthenticated ? 'trending' : mode;

  try {
    if (topic) {
      // Search mode active
      exploreData = await fetchApi(`/explore/search?topic=${encodeURIComponent(topic)}&limit=10${sort ? `&sort=${sort}` : ''}${trending ? `&trending=true` : ''}`);
    } else if (activeMode === 'for_you') {
      exploreData = await fetchApi('/explore/for-you?limit=10');
      forYouData = exploreData; // use the same data for featured section if needed
    } else {
      exploreData = await fetchApi(`/explore?limit=10&mode=${activeMode}${sort ? `&sort=${sort}` : ''}${trending ? `&trending=true` : ''}`);
      if (isAuthenticated) {
        forYouData = await fetchApi('/explore/for-you?limit=2');
      } else {
        forYouData = await fetchApi('/explore?mode=trending&limit=2');
      }
    }
  } catch (error) {
    console.error("Failed to fetch explore data:", error);
  }

  const items = exploreData?.data || [];
  const nextCursor = exploreData?.nextCursor || null;
  const signals = exploreData?.signals;
  
  // Featured items only show if we are NOT in search and NOT in for_you mode
  const showFeatured = !topic && activeMode !== 'for_you';
  const featuredItems = forYouData?.data || [];
  const displayFeatured1 = featuredItems[0];
  const displayFeatured2 = featuredItems[1];

  const tabs = [
    ...(isAuthenticated ? [{ id: 'for_you', label: 'For You', icon: Sparkles }] : []),
    { id: 'trending', label: 'Trending', icon: Flame },
    { id: 'top', label: 'Top', icon: Star },
    { id: 'new', label: 'New', icon: Clock }
  ];

  return (
    <MainLayout activePage="explore">
      <div className="max-w-6xl mx-auto">
        {/* Page Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-8 gap-4">
          <div className="max-w-xl">
            <h2 className="text-3xl font-bold text-slate-900 mb-2">{topic ? `Search: ${topic}` : "Explore"}</h2>
            <p className="text-slate-500 text-sm">
              {topic ? "Showing results for your topic." : "Discover the latest cinematic masterpieces generated by the Neura Gen community."}
            </p>
          </div>

          <div className="flex flex-col sm:flex-row items-center gap-4">
            <ExploreSearch />
          </div>
        </div>
        
        {/* Mode Tabs */}
        {!topic && (
          <div className="flex overflow-x-auto hide-scrollbar mb-8 pb-2">
            <div className="flex bg-white/50 backdrop-blur-md p-1.5 rounded-2xl border border-slate-200/60 shadow-sm">
              {tabs.map(tab => {
                const Icon = tab.icon;
                const isActive = activeMode === tab.id;
                return (
                  <Link 
                    key={tab.id}
                    href={`?mode=${tab.id}`}
                    className={`flex items-center gap-2 px-5 py-2.5 text-sm font-semibold rounded-xl transition-all duration-300 ${
                      isActive 
                        ? 'bg-white text-indigo-600 shadow-[0_2px_10px_rgba(0,0,0,0.06)]' 
                        : 'text-slate-500 hover:text-slate-700 hover:bg-slate-50'
                    }`}
                  >
                    <Icon size={16} className={isActive ? "text-indigo-600" : "text-slate-400"} />
                    {tab.label}
                  </Link>
                );
              })}
            </div>
          </div>
        )}

        {/* Featured Section */}
        {showFeatured && (
          <div className="mb-12">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Sparkles className="h-5 w-5 text-indigo-600" />
                <h3 className="text-xl font-bold text-slate-900">Featured Spotlights</h3>
              </div>
            </div>

            {displayFeatured1 || displayFeatured2 ? (
              <div className="grid grid-cols-12 gap-6 h-[400px]">
                {/* Featured Card Left */}
                {displayFeatured1 && (
                  <div className="col-span-12 md:col-span-8 relative rounded-[2rem] overflow-hidden group cursor-pointer shadow-lg block border border-slate-100">
                    <Link href={`/post/${displayFeatured1.postId || displayFeatured1.id}`} className="absolute inset-0 z-10" />
                    {(() => {
                      const videoUrl = displayFeatured1.videoUrl || displayFeatured1.post?.videoUrl || displayFeatured1.assetVersion?.fileUrl;
                      const thumbnailUrl = displayFeatured1.thumbnailUrl || displayFeatured1.post?.thumbnailUrl;
                      const isVideo = !!videoUrl && (displayFeatured1.assetVersion?.mimeType?.startsWith('video/') || /\.(mp4|webm|mov)(\?|$)/i.test(videoUrl));
                      const displayUrl = videoUrl || "https://images.unsplash.com/photo-1605806616949-1e87b487cb2a?auto=format&fit=crop&q=80&w=1200";
                      
                      return isVideo ? (
                        <video src={displayUrl} poster={thumbnailUrl || "https://images.unsplash.com/photo-1605806616949-1e87b487cb2a?auto=format&fit=crop&q=80&w=1200"} className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" autoPlay loop muted playsInline />
                      ) : (
                        <img src={thumbnailUrl || displayUrl} alt={displayFeatured1.title || "Featured Video"} className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" />
                      );
                    })()}
                    <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-transparent p-8 flex flex-col justify-end pointer-events-none">
                      <div className="mb-auto mt-2 pointer-events-auto relative z-20 w-fit">
                        <span className="bg-white/20 backdrop-blur-md text-white text-xs font-bold px-4 py-1.5 rounded-full tracking-wider border border-white/30 shadow-sm uppercase">
                          {isAuthenticated ? 'Recommended' : 'Trending'}
                        </span>
                      </div>
                      <div className="flex justify-between items-end pointer-events-auto relative z-20">
                        <div>
                          <h4 className="text-3xl md:text-4xl font-extrabold text-white mb-4 leading-tight">
                            {displayFeatured1.title || "Untitled Video"}
                          </h4>
                          <Link href={`/user/${displayFeatured1.post?.user?.id || displayFeatured1.post?.user?.username || 'unknown'}`} className="flex items-center gap-3 text-white/90 hover:text-white transition-colors w-fit bg-black/20 backdrop-blur-sm pr-4 py-1.5 pl-1.5 rounded-full border border-white/10">
                            <img
                              src={displayFeatured1.post?.user?.avatarUrl || `https://ui-avatars.com/api/?name=${encodeURIComponent(displayFeatured1.post?.user?.username || "Creator")}&background=e0e7ff&color=4f46e5`}
                              alt="Creator"
                              className="w-8 h-8 rounded-full border-2 border-white/80 object-cover bg-slate-100"
                            />
                            <p className="font-semibold text-sm tracking-wide">{displayFeatured1.post?.user?.username || "Unknown Creator"}</p>
                          </Link>
                        </div>
                        <button className="bg-white/20 backdrop-blur-md hover:bg-white/30 text-white rounded-full p-4 transition-all duration-300 hover:scale-110 shadow-lg border border-white/20">
                          <Play className="h-6 w-6 fill-current" />
                        </button>
                      </div>
                    </div>
                  </div>
                )}

                {/* Secondary Card Right */}
                {displayFeatured2 && (
                  <div className="hidden md:block col-span-4 relative rounded-[2rem] overflow-hidden group cursor-pointer shadow-lg border border-slate-100">
                    <Link href={`/post/${displayFeatured2.postId || displayFeatured2.id}`} className="absolute inset-0 z-10" />
                    {(() => {
                      const videoUrl = displayFeatured2.videoUrl || displayFeatured2.post?.videoUrl || displayFeatured2.assetVersion?.fileUrl;
                      const thumbnailUrl = displayFeatured2.thumbnailUrl || displayFeatured2.post?.thumbnailUrl;
                      const isVideo = !!videoUrl && (displayFeatured2.assetVersion?.mimeType?.startsWith('video/') || /\.(mp4|webm|mov)(\?|$)/i.test(videoUrl));
                      const displayUrl = videoUrl || "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800";
                      
                      return isVideo ? (
                        <video src={displayUrl} poster={thumbnailUrl || "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800"} className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" autoPlay loop muted playsInline />
                      ) : (
                        <img src={thumbnailUrl || displayUrl} alt={displayFeatured2.title || "Featured Video"} className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" />
                      );
                    })()}
                    <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent p-6 flex flex-col justify-end pointer-events-none">
                      <h4 className="text-2xl font-bold text-white mb-3 relative z-20 leading-tight">
                        {displayFeatured2.title || "Untitled Video"}
                      </h4>
                      <Link href={`/user/${displayFeatured2.post?.user?.id || displayFeatured2.post?.user?.username || 'unknown'}`} className="text-white/80 text-sm font-medium hover:text-white transition-colors relative z-20 w-fit pointer-events-auto">
                        @{displayFeatured2.post?.user?.username || "unknown"}
                      </Link>
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className="w-full h-40 flex items-center justify-center border border-slate-100 rounded-[2rem] bg-slate-50 text-slate-400 font-medium">
                Check back later for personalized recommendations.
              </div>
            )}
          </div>
        )}

        {/* Recent Discoveries Section */}
        <div>
          <div className="flex items-center gap-2 mb-6">
            <Compass className="h-5 w-5 text-indigo-600" />
            <h3 className="text-xl font-bold text-slate-900">
              {topic ? "Search Results" : (activeMode === 'for_you' ? 'Recommended For You' : 'Recent Discoveries')}
            </h3>
          </div>

          <ExploreFeed 
            initialItems={items} 
            initialCursor={nextCursor} 
            mode={activeMode} 
            topic={topic} 
            sort={sort}
            trending={trending}
            signals={signals}
          />
        </div>
      </div>
      <ExplorePublishButton jobs={userJobs} isAuthenticated={isAuthenticated} />
    </MainLayout>
  );
}
